### ISSUE TITLE
Si el servicio Comprobantes en Línea no está en pantalla no puede continuar.

### ISSUE THREAD

**Issue by fjbotto** [xaavito/botter#6]
Mi HOME de Afip
![image](https://user-images.githubusercontent.com/5702873/185018619-bb1bc2a4-7b9a-4904-a06f-937427a41db4.png)

Para eso hay que agregar un paso antes de [Comprobantes den Línea](https://github.com/xaavito/botter/blob/master/index.js#L31)
```
  await page.click('text=Ver todos');
  await page.waitForTimeout(1000);
```

**Comment by xaavito** [comment]
Fixed
